2025-04-27 15:41:25 ERROR: uncaughtException: Cannot read properties of undefined (reading 'use_env_variable')
TypeError: Cannot read properties of undefined (reading 'use_env_variable')
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\models\index.js:13:12)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:9:23) 
TypeError: Cannot read properties of undefined (reading 'use_env_variable')
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\models\index.js:13:12)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:9:23)
2025-04-27 15:42:57 ERROR: uncaughtException: roleMiddleware is not a function
TypeError: roleMiddleware is not a function
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\moduleRoutes.js:212:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:16:22) 
TypeError: roleMiddleware is not a function
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\moduleRoutes.js:212:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:16:22)
2025-04-27 15:46:12 ERROR: uncaughtException: Route.post() requires a callback function but got a [object Object]
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\moduleRoutes.js:210:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\moduleRoutes.js:210:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-04-27 15:47:56 ERROR: uncaughtException: Route.post() requires a callback function but got a [object Object]
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\moduleRoutes.js:153:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\moduleRoutes.js:153:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-04-27 15:50:52 ERROR: uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as put] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:290:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as put] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:290:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-04-27 23:25:15 ERROR: uncaughtException: Route.post() requires a callback function but got a [object Object]
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\authRoutes.js:179:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\authRoutes.js:179:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-04-27 23:26:01 ERROR: uncaughtException: Route.post() requires a callback function but got a [object Object]
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\authRoutes.js:179:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.post() requires a callback function but got a [object Object]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\authRoutes.js:179:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-04-27 23:35:40 ERROR: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:384:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:384:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-04-27 23:39:13 ERROR: uncaughtException: Router.use() requires a middleware function
TypeError: Router.use() requires a middleware function
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:462:11)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\evenementRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16) 
TypeError: Router.use() requires a middleware function
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:462:11)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\evenementRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-05-13 11:02:46 ERROR: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:94:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14) 
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:94:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-05-13 11:18:07 ERROR: uncaughtException: Unexpected token '}'
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\adminController.js:253
  } catch (error) {
  ^

SyntaxError: Unexpected token '}'
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\adminRoutes.js:5:25) 
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\adminController.js:253
  } catch (error) {
  ^

SyntaxError: Unexpected token '}'
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\adminRoutes.js:5:25)
2025-05-13 11:39:07 ERROR: uncaughtException: Unexpected identifier 'tableName'
D:\Site Web\les audacieuses\AudacieusesAPI\src\models\activite.js:29
    tableName: 'activites',
    ^^^^^^^^^

SyntaxError: Unexpected identifier 'tableName'
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at D:\Site Web\les audacieuses\AudacieusesAPI\src\models\index.js:28:19 
D:\Site Web\les audacieuses\AudacieusesAPI\src\models\activite.js:29
    tableName: 'activites',
    ^^^^^^^^^

SyntaxError: Unexpected identifier 'tableName'
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at D:\Site Web\les audacieuses\AudacieusesAPI\src\models\index.js:28:19
2025-05-13 12:38:15 ERROR: uncaughtException: Missing catch or finally after try
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\seanceController.js:165
    }
    ^

SyntaxError: Missing catch or finally after try
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:5:26) 
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\seanceController.js:165
    }
    ^

SyntaxError: Missing catch or finally after try
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:5:26)
2025-05-13 12:38:32 ERROR: uncaughtException: Missing catch or finally after try
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\seanceController.js:165
    }
    ^

SyntaxError: Missing catch or finally after try
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:5:26) 
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\seanceController.js:165
    }
    ^

SyntaxError: Missing catch or finally after try
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:5:26)
2025-05-13 12:38:44 ERROR: uncaughtException: Missing catch or finally after try
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\seanceController.js:173
    }
    ^

SyntaxError: Missing catch or finally after try
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:5:26) 
D:\Site Web\les audacieuses\AudacieusesAPI\src\controllers\seanceController.js:173
    }
    ^

SyntaxError: Missing catch or finally after try
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\seanceRoutes.js:5:26)
2025-05-13 13:13:00 ERROR: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:96:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14) 
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:96:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2025-05-13 13:15:14 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 13:30:57 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 13:34:26 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 13:34:32 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 13:36:58 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 13:37:07 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 13:50:24 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 13:51:24 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 16:54:22 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 16:54:41 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 17:19:54 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 17:20:48 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 17:20:56 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 17:21:09 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 17:23:49 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 17:24:51 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-13 17:26:25 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-14 10:29:27 ERROR: uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\Site Web\les audacieuses\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-14 10:36:30 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:17)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:68:17)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:36:34 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:91:22)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:91:22)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:36:39 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:127:33)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:127:33)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:36:43 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:176:18)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:176:18)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:36:48 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:226:20)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:226:20)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:36:53 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:253:23)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:253:23)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:36:58 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:302:42)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:302:42)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:37:03 ERROR: uncaughtException: auth is not defined
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:329:20)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24) 
ReferenceError: auth is not defined
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\routes\activiteRoutes.js:329:20)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:23:24)
2025-05-14 10:37:52 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:570:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses\AudacieusesAPI\src\app.js:570:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 11:56:25 ERROR: uncaughtException: Cannot find module '../config/sequelize'
Require stack:
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\controllers\moduleController.js
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\moduleRoutes.js
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js
Error: Cannot find module '../config/sequelize'
Require stack:
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\controllers\moduleController.js
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\moduleRoutes.js
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\controllers\moduleController.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32) 
Error: Cannot find module '../config/sequelize'
Require stack:
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\controllers\moduleController.js
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\moduleRoutes.js
- D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\controllers\moduleController.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-05-14 14:06:11 ERROR: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\moduleRoutes.js:680:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12) 
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\moduleRoutes.js:680:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
2025-05-14 14:08:44 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 14:25:46 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 14:59:53 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 15:01:05 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 15:01:43 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 15:05:14 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 15:11:24 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-05-14 15:12:18 ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\app.js:582:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-14 17:45:15] ERROR: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\activiteRoutes.js:360:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-14 17:45:20] ERROR: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\activiteRoutes.js:360:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-14 17:46:04] ERROR: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\Site Web\les audacieuses - Copie\AudacieusesAPI\src\routes\activiteRoutes.js:360:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:04:24] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-16 17:39:56] ERROR: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\activiteRoutes.js:437:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:43:27] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:43:35] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:43:42] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:43:50] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:44:16] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:44:36] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-16 17:44:50] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-17 01:32:29] ERROR: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\seanceRoutes.js:368:8)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-18 16:37:12] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 16:49:36] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 16:54:50] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 16:59:57] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 17:05:24] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 17:58:58] ERROR: uncaughtException: require(...) is not a function
TypeError: require(...) is not a function
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:28:54
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\models\index.js:27:4)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
[2025-05-18 18:00:25] ERROR: uncaughtException: Cannot find module '../config/logger'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\controllers\seanceController.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\seanceRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module '../config/logger'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\controllers\seanceController.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\seanceRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 18:01:30] ERROR: uncaughtException: Cannot find module '../config/logger'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\controllers\seanceController.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\seanceRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module '../config/logger'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\controllers\seanceController.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\seanceRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 18:02:00] ERROR: uncaughtException: Cannot find module '../config/logger'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\controllers\seanceController.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\seanceRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module '../config/logger'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\controllers\seanceController.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\seanceRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\helpers\moduleProgressionHelper.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 19:16:34] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 19:28:01] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 19:29:47] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 19:46:44] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:583:12
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-05-18 19:59:22] ERROR: uncaughtException: Cannot find module '../controllers/messageController'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\messageRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module '../controllers/messageController'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\messageRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\messageRoutes.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 19:59:28] ERROR: uncaughtException: Cannot find module '../controllers/messageController'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\messageRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module '../controllers/messageController'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\messageRoutes.js
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\routes\messageRoutes.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 19:59:35] ERROR: uncaughtException: Cannot find module './routes/messageRoutes'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module './routes/messageRoutes'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:20:23)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 19:59:41] ERROR: uncaughtException: Cannot find module './routes/messageRoutes'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module './routes/messageRoutes'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:20:23)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 20:00:52] ERROR: uncaughtException: Cannot find module './routes/messageRoutes'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
Error: Cannot find module './routes/messageRoutes'
Require stack:
- E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:20:23)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
[2025-05-18 20:01:25] ERROR: uncaughtException: messageRoutes is not defined
ReferenceError: messageRoutes is not defined
    at Object.<anonymous> (E:\site web\Audacieuses-main\Audacieuses-main\AudacieusesAPI\src\app.js:105:26)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
